[package]
name = "kelo-liquidity-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.9.5"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
borsh = "0.9.1"
thiserror = "1.0.30"
