[package]
name = "KeloLiquidityPool"
version = "1.0.0"
author = ["Kelo Finance"]

[addresses]
KeloLiquidityPool = "0x..."

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
